// <auto-generated />
using CodeFirstApproach;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeFirstApproach.Migrations
{
    [DbContext(typeof(ExampleContext))]
    [Migration("20260115104714_Examples5_c")]
    partial class Examples5_c
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CodeFirstApproach.Example", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Examples");
                });

            modelBuilder.Entity("CodeFirstApproach.Example2", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Examples2");
                });

            modelBuilder.Entity("CodeFirstApproach.Example3", b =>
                {
                    b.Property<int>("Nr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Nr");

                    b.ToTable("Examples3");
                });

            modelBuilder.Entity("CodeFirstApproach.Example4", b =>
                {
                    b.Property<int>("Nr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Nr")
                        .HasName("PRIMARY");

                    b.ToTable("Examples4");
                });

            modelBuilder.Entity("CodeFirstApproach.Example5", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Value1")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Value2")
                        .HasColumnType("longtext");

                    b.Property<string>("Value4")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Value5")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Value6")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Value7")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Value8")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Value9")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Examples5");
                });
#pragma warning restore 612, 618
        }
    }
}
